#!/bin/sh -e
# bzip2 has no configure and no usable install target; this mirrors
# Void's do_build/do_install by hand. The soname patch (auto-applied
# from patches/) changes libbz2's soname to libbz2.so.1 to match the
# ABI every Void-built consumer (freetype, ...) expects.

make CFLAGS="-O2 -fPIC $CPPFLAGS $LDFLAGS" LDFLAGS="$LDFLAGS" -f Makefile-libbz2_so
make CFLAGS="-O2 $CPPFLAGS" LDFLAGS="$LDFLAGS" bzip2recover libbz2.a

bin="$1$CHY_ROOT/usr/bin"
lib="$1$CHY_ROOT/usr/lib"
mkdir -p "$bin" "$lib"

install -m755 bzip2-shared "$bin/bzip2"
install -m755 bzip2recover "$bin/bzip2recover"
ln -sf bzip2 "$bin/bunzip2"
ln -sf bzip2 "$bin/bzcat"
install -m755 bzdiff bzgrep bzmore "$bin"

install -m755 libbz2.so.1.0.8 "$lib/libbz2.so.1.0.8"
ln -sf libbz2.so.1.0.8 "$lib/libbz2.so"
ln -sf libbz2.so.1.0.8 "$lib/libbz2.so.1"
ln -sf libbz2.so.1.0.8 "$lib/libbz2.so.1.0"
install -m644 libbz2.a "$lib/libbz2.a"
install -Dm644 bzlib.h "$1$CHY_ROOT/usr/include/bzlib.h"

mkdir -p "$lib/pkgconfig"
cat > "$lib/pkgconfig/bzip2.pc" <<PC
prefix=$CHY_PREFIX
exec_prefix=\${prefix}
bindir=\${exec_prefix}/bin
libdir=\${exec_prefix}/lib
includedir=\${prefix}/include

Name: bzip2
Description: A file compression library
Version: 1.0.8
Libs: -L\${libdir} -lbz2
Cflags: -I\${includedir}
PC

install -Dm644 bzip2.1 "$1$CHY_ROOT/usr/share/man/man1/bzip2.1"
ln -sf bzip2.1 "$1$CHY_ROOT/usr/share/man/man1/bunzip2.1"
ln -sf bzip2.1 "$1$CHY_ROOT/usr/share/man/man1/bzcat.1"
